ci: refactor workflow to build kernel without build.sh
Signed-off-by: Prslc <prslc113@gmail.com>

diff --git a/.github/workflows/Build_Kernel.yml b/.github/workflows/Build_Kernel.yml
--- a/.github/workflows/Build_Kernel.yml
+++ b/.github/workflows/Build_Kernel.yml
@@ -1,3 +1,9 @@
+# This workflows build script references and adapts logic from:
+# - [scripts/build_kernel] by UtsavBalar1231
+# - [build.sh] by liyafe1997
+# - [.github/workflows/Build_Kernel.yml] by yspbwx2010
+# Many thanks to their authors for the inspiration.
+
 name: Build Kernel
 
 on:
@@ -30,18 +36,23 @@ on:
         options:
           - 'aosp'
           - 'miui'
-          - 'all'
 
       kernelsu_version:
         description: 'KernelSU Version'
         required: true
         type: choice
-        default: 'sukisu-ultra'
+        default: 'noksu'
         options:
           - 'ksu'
           - 'rksu'
           - 'sukisu'
-          - 'sukisu-kpm'
+          - 'noksu'
+
+      enable_kpm:
+        description: 'Enable KPM (only SukiSU)'
+        required: true
+        type: boolean
+        default: false
 
 jobs:
   build:
@@ -69,41 +80,288 @@ jobs:
       - name: Download Proton Clang Toolchain
         if: steps.clang-cache.outputs.cache-hit != 'true'
         run: |
-          mkdir -p toolchain; cd toolchain
-          wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
-          unzip 20210522.zip
-          mv proton-clang-20210522 proton-clang
-          rm proton-clang/bin/ld 20210522.zip
+          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git toolchain/proton-clang
+          rm -f toolchain/proton-clang/bin/ld
           
       - name: Cache ccache
         uses: actions/cache@v4
         with:
           path: ~/.cache/ccache_mikernel
-          key: ${{ runner.os }}-ccache-${{ github.event.inputs.target_device }}-${{ github.sha }}
+          key: ${{ runner.os }}-ccache-${{ github.event.inputs.target_device }}-${{ github.event.inputs.system_version }}
           restore-keys: |
-            ${{ runner.os }}-ccache-${{ github.event.inputs.target_device }}-
+            ${{ runner.os }}-ccache-
 
       - name: Build Kernel
         run: |
-          sed -i 's|TOOLCHAIN_PATH=\$HOME/toolchain/proton-clang/bin|TOOLCHAIN_PATH=$(pwd)/toolchain/proton-clang/bin|' build.sh
-          DEVICE="${{ github.event.inputs.target_device }}"
-          SYSTEM="${{ github.event.inputs.system_version }}"
-          KSU_VERSION="${{ github.event.inputs.kernelsu_version }}"
-          bash build.sh "$DEVICE" "$KSU_VERSION" "$SYSTEM"
+          TOOLCHAIN_PATH=$(pwd)/toolchain/proton-clang/bin
+          TARGET_DEVICE=${{ github.event.inputs.target_device }}
+          export PATH="$TOOLCHAIN_PATH:$PATH"
 
-      - name: Set Kernel Path
-        run: |
-          if [[ "${{ github.event.inputs.system_version }}" == "aosp" || "${{ github.event.inputs.system_version }}" == "miui" ]]; then
-              KernelPath=$(ls Kernel_* 2>/dev/null || true)
-              echo "KernelPath=$(pwd)/$KernelPath" >> $GITHUB_ENV
-          else
-              tar -czvf Kernel_All.tar.gz Kernel_*
-              KernelPath=$(pwd)/Kernel_All.tar.gz
-              echo "KernelPath=$KernelPath" >> $GITHUB_ENV
+          # Enable ccache for speed up compiling
+          export CCACHE_DIR="$HOME/.cache/ccache_mikernel"
+          export PATH="/usr/lib/ccache:$PATH"
+          echo "CCACHE_DIR: [$CCACHE_DIR]"
+
+          MAKE_ARGS="ARCH=arm64 \
+              SUBARCH=arm64 \
+              O=out \
+              CC=clang \
+              CROSS_COMPILE=aarch64-linux-gnu- \
+              CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
+              CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
+              CLANG_TRIPLE=aarch64-linux-gnu-"
+
+          if [ ! -f "arch/arm64/configs/${TARGET_DEVICE}_defconfig" ]; then
+              echo "No target device [${TARGET_DEVICE}] found."
+              echo "Available defconfigs, please choose one target from below:"
+              ls arch/arm64/configs/*_defconfig
+              exit 1
           fi
+
+          # Initialize variables
+          KERNEL_SRC=$(pwd)
+          KPM_ENABLE=${{ github.event.inputs.enable_kpm }}
+          KSU_VERSION=${{ github.event.inputs.kernelsu_version }}
+          TARGET_SYSTEM=${{ github.event.inputs.system_version }}
+
+          KSU_ENABLE=$([[ "$KSU_VERSION" == "ksu" || "$KSU_VERSION" == "rksu" || "$KSU_VERSION" == "sukisu" ]] && echo 1 || echo 0)
+
+          # KernelSU setup
+          case "$KSU_VERSION" in
+              ksu)
+                  KSU_ZIP_STR=KernelSU
+                  echo "KSU is enabled"
+                  curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
+                  ;;
+              rksu)
+                  KSU_ZIP_STR=RKSU
+                  echo "RKSU is enabled"
+                  curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
+                  ;;
+              sukisu)
+                  KSU_ZIP_STR=SukiSU
+                  echo "SukiSU is enabled"
+                  curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s nongki
+                  ;;
+              *)
+                  KSU_ZIP_STR=NoKernelSU
+                  echo "KSU is disabled"
+                  ;;
+          esac
+
+          git clone https://github.com/liyafe1997/AnyKernel3 -b kona --single-branch --depth=1 anykernel
+
+          Build_AOSP() {
+              echo "Building for AOSP......"
+              make $MAKE_ARGS ${TARGET_DEVICE}_defconfig
+              SET_CONFIG
+              make $MAKE_ARGS -j$(nproc)
+              Image_Repack
+              echo "Build for AOSP finished."
+          }
+
+          Build_MIUI(){
+              echo "Clearning [out/] and build for MIUI....."
+              rm -rf out/
+
+              dts_source=arch/arm64/boot/dts/vendor/qcom
+
+              # Backup dts
+              cp -a ${dts_source} .dts.bak
+
+              # Correct panel dimensions on MIUI builds
+              sed -i 's/<154>/<1537>/g' ${dts_source}/dsi-panel-j1s*
+              sed -i 's/<154>/<1537>/g' ${dts_source}/dsi-panel-j2*
+              sed -i 's/<155>/<1544>/g' ${dts_source}/dsi-panel-j3s-37-02-0a-dsc-video.dtsi
+              sed -i 's/<155>/<1545>/g' ${dts_source}/dsi-panel-j11-38-08-0a-fhd-cmd.dtsi
+              sed -i 's/<155>/<1546>/g' ${dts_source}/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi
+              sed -i 's/<155>/<1546>/g' ${dts_source}/dsi-panel-l11r-38-08-0a-dsc-cmd.dtsi
+              sed -i 's/<70>/<695>/g' ${dts_source}/dsi-panel-j11-38-08-0a-fhd-cmd.dtsi
+              sed -i 's/<70>/<695>/g' ${dts_source}/dsi-panel-j3s-37-02-0a-dsc-video.dtsi
+              sed -i 's/<70>/<695>/g' ${dts_source}/dsi-panel-k11a-38-08-0a-dsc-cmd.dtsi
+              sed -i 's/<70>/<695>/g' ${dts_source}/dsi-panel-l11r-38-08-0a-dsc-cmd.dtsi
+              sed -i 's/<71>/<710>/g' ${dts_source}/dsi-panel-j1s*
+              sed -i 's/<71>/<710>/g' ${dts_source}/dsi-panel-j2*
+
+              # Enable back mi smartfps while disabling qsync min refresh-rate
+              sed -i 's/\/\/ mi,mdss-dsi-pan-enable-smart-fps/mi,mdss-dsi-pan-enable-smart-fps/g' ${dts_source}/dsi-panel*
+              sed -i 's/\/\/ mi,mdss-dsi-smart-fps-max_framerate/mi,mdss-dsi-smart-fps-max_framerate/g' ${dts_source}/dsi-panel*
+              sed -i 's/\/\/ qcom,mdss-dsi-pan-enable-smart-fps/qcom,mdss-dsi-pan-enable-smart-fps/g' ${dts_source}/dsi-panel*
+              sed -i 's/qcom,mdss-dsi-qsync-min-refresh-rate/\/\/qcom,mdss-dsi-qsync-min-refresh-rate/g' ${dts_source}/dsi-panel*
+
+              # Enable back refresh rates supported on MIUI
+              sed -i 's/120 90 60/120 90 60 50 30/g' ${dts_source}/dsi-panel-g7a-36-02-0c-dsc-video.dtsi
+              sed -i 's/120 90 60/120 90 60 50 30/g' ${dts_source}/dsi-panel-g7a-37-02-0a-dsc-video.dtsi
+              sed -i 's/120 90 60/120 90 60 50 30/g' ${dts_source}/dsi-panel-g7a-37-02-0b-dsc-video.dtsi
+              sed -i 's/144 120 90 60/144 120 90 60 50 48 30/g' ${dts_source}/dsi-panel-j3s-37-02-0a-dsc-video.dtsi
+
+              # Enable back brightness control from dtsi
+              sed -i 's/\/\/39 00 00 00 00 00 03 51 03 FF/39 00 00 00 00 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j9-38-0a-0a-fhd-video.dtsi
+              sed -i 's/\/\/39 00 00 00 00 00 03 51 0D FF/39 00 00 00 00 00 03 51 0D FF/g' ${dts_source}/dsi-panel-j2-p2-1-38-0c-0a-dsc-cmd.dtsi
+              sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j1s-42-02-0a-dsc-cmd.dtsi
+              sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j1s-42-02-0a-mp-dsc-cmd.dtsi
+              sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j2-mp-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j2-p2-1-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 00 00 00 00 00 05 51 0F 8F 00 00/39 00 00 00 00 00 05 51 0F 8F 00 00/g' ${dts_source}/dsi-panel-j2s-mp-42-02-0a-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 00 00/39 01 00 00 00 00 03 51 00 00/g' ${dts_source}/dsi-panel-j2-38-0c-0a-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 00 00/39 01 00 00 00 00 03 51 00 00/g' ${dts_source}/dsi-panel-j2-38-0c-0a-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 03 FF/39 01 00 00 00 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j11-38-08-0a-fhd-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 03 FF/39 01 00 00 00 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j9-38-0a-0a-fhd-video.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 07 FF/39 01 00 00 00 00 03 51 07 FF/g' ${dts_source}/dsi-panel-j1u-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 07 FF/39 01 00 00 00 00 03 51 07 FF/g' ${dts_source}/dsi-panel-j2-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 07 FF/39 01 00 00 00 00 03 51 07 FF/g' ${dts_source}/dsi-panel-j2-p1-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 0F FF/39 01 00 00 00 00 03 51 0F FF/g' ${dts_source}/dsi-panel-j1u-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 0F FF/39 01 00 00 00 00 03 51 0F FF/g' ${dts_source}/dsi-panel-j2-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 03 51 0F FF/39 01 00 00 00 00 03 51 0F FF/g' ${dts_source}/dsi-panel-j2-p1-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j1s-42-02-0a-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j1s-42-02-0a-mp-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j2-mp-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j2-p2-1-42-02-0b-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 00 00 05 51 07 FF 00 00/39 01 00 00 00 00 05 51 07 FF 00 00/g' ${dts_source}/dsi-panel-j2s-mp-42-02-0a-dsc-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 01 00 03 51 03 FF/39 01 00 00 01 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j11-38-08-0a-fhd-cmd.dtsi
+              sed -i 's/\/\/39 01 00 00 11 00 03 51 03 FF/39 01 00 00 11 00 03 51 03 FF/g' ${dts_source}/dsi-panel-j2-p2-1-38-0c-0a-dsc-cmd.dtsi
+
+              make $MAKE_ARGS ${TARGET_DEVICE}_defconfig
+
+              SET_CONFIG MIUI
+
+              make $MAKE_ARGS -j$(nproc)
+
+              Image_Repack MIUI
+          }
+
+          SET_CONFIG() {
+              if [ "$1" == "MIUI" ]; then
+                  scripts/config --file out/.config \
+                      --set-str STATIC_USERMODEHELPER_PATH /system/bin/micd \
+                      -e PERF_CRITICAL_RT_TASK \
+                      -e SF_BINDER \
+                      -e OVERLAY_FS \
+                      -d DEBUG_FS \
+                      -e MIGT \
+                      -e MIGT_ENERGY_MODEL \
+                      -e MIHW \
+                      -e PACKAGE_RUNTIME_INFO \
+                      -e BINDER_OPT \
+                      -e KPERFEVENTS \
+                      -e MILLET \
+                      -e PERF_HUMANTASK \
+                      -d LTO_CLANG \
+                      -d LOCALVERSION_AUTO \
+                      -e SF_BINDER \
+                      -e XIAOMI_MIUI \
+                      -d MI_MEMORY_SYSFS \
+                      -e TASK_DELAY_ACCT \
+                      -e MIUI_ZRAM_MEMORY_TRACKING \
+                      -d CONFIG_MODULE_SIG_SHA512 \
+                      -d CONFIG_MODULE_SIG_HASH \
+                      -e MI_FRAGMENTION \
+                      -e PERF_HELPER \
+                      -e BOOTUP_RECLAIM \
+                      -e MI_RECLAIM \
+                      -e RTMM
+              fi
+
+              if [ "$KSU_ENABLE" -eq 1 ]; then
+                  scripts/config --file out/.config -e KSU
+              else
+                  scripts/config --file out/.config -d KSU
+              fi
+
+              # Enable the KSU_MANUAL_HOOK for SukiSU and RKSU
+              if [[ "$KSU_VERSION" == "sukisu" || "$KSU_VERSION" == "rksu" ]]; then
+                  scripts/config --file out/.config -e KSU_MANUAL_HOOK
+              else
+                  scripts/config --file out/.config -d KSU_MANUAL_HOOK
+              fi
+
+              # Config KPM
+              if [ "$KPM_ENABLE" == "true" ]; then
+                  scripts/config --file out/.config \
+                      -e KPM \
+                      -e KALLSYMS \
+                      -e KALLSYMS_ALL
+              else
+                  scripts/config --file out/.config \
+                      -d KPM \
+                      -d KALLSYMS \
+                      -d KALLSYMS_ALL
+              fi
+          }
+
+          Patch_KPM() {
+              cd out/arch/arm64/boot
+              curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU_patch/refs/heads/main/kpm/patch_linux" -o patch
+              chmod +x patch
+              ./patch
+
+              if [ $? -eq 0 ]; then
+                  rm -f Image
+                  mv oImage Image
+                  echo "Image file repair complete"
+              else
+                  echo "KPM Patch Failed, Use Original Image"
+              fi
+
+              cd $KERNEL_SRC
+          }
+
+          Image_Repack() {
+              if [ -f "out/arch/arm64/boot/Image" ]; then
+                  echo "The file [out/arch/arm64/boot/Image] exists. Build successfully."
+              else
+                  echo "The file [out/arch/arm64/boot/Image] does not exist. Seems build failed."
+                  exit 1
+              fi
+
+              # KPM Patch
+              if [[ "$KPM_ENABLE" == 'true' && "$KSU_VERSION" == "sukisu" ]]; then
+                  Patch_KPM
+              fi
+
+              echo "Generating [out/arch/arm64/boot/dtb]......"
+              find out/arch/arm64/boot/dts -name '*.dtb' -exec cat {} + >out/arch/arm64/boot/dtb
+
+              # Restore modified dts
+              if [ "$1" == "MIUI" ]; then
+                  rm -rf ${dts_source}
+                  mv .dts.bak ${dts_source}
+              fi
+
+              rm -rf anykernel/kernels/
+              mkdir -p anykernel/kernels/
+              cp out/arch/arm64/boot/Image anykernel/kernels/
+              cp out/arch/arm64/boot/dtb anykernel/kernels/
+              cd anykernel
+
+              if [ "$1" == "MIUI" ]; then
+                  ZIP_FILENAME=Kernel_MIUI_${TARGET_DEVICE}_${KSU_ZIP_STR}_$(date +'%Y%m%d_%H%M%S')_anykernel3.zip
+              else
+                  ZIP_FILENAME=Kernel_AOSP_${TARGET_DEVICE}_${KSU_ZIP_STR}_$(date +'%Y%m%d_%H%M%S')_anykernel3.zip
+              fi
+
+              zip -r9 $ZIP_FILENAME ./* -x .git .gitignore out/ ./*.zip
+              mv $ZIP_FILENAME ../
+              cd ..
+              echo "Done. The flashable zip is: [./$ZIP_FILENAME]"
+          }
+
+          if [ "$TARGET_SYSTEM" == "aosp" ]; then
+              Build_AOSP
+          elif [ "$TARGET_SYSTEM" == "miui" ]; then
+              Build_MIUI
+          fi
+
+          echo "::group::Build Summary"
+          echo "Target Device : $TARGET_DEVICE"
+          echo "System Version: $TARGET_SYSTEM"
+          echo "KernelSU Ver  : $KSU_VERSION"
+          echo "KPM Enabled   : $KPM_ENABLE"
+          echo "CCACHE Used   : $(ccache -s | grep 'cache hit (direct)' || true)"
+          echo "::endgroup::"
       
       - name: Upload Kernel
         uses: actions/upload-artifact@v4
         with:
-          name: Kernel
-          path: ${{ env.KernelPath }}
+          name: Kernel_${{ github.event.inputs.target_device }}_${{ github.event.inputs.system_version }}_${{ github.event.inputs.kernelsu_version }}
+          path: ./*.zip
